### ISSUE TITLE
does not work on web release by default

### ISSUE THREAD

**Issue by miklcct** [tjarvstrand/flutter_timezone#26]
I followed the instruction to install the package. It works in debug mode in Chrome but crashed in release mode.

It says
```
Uncaught MissingPluginException(No implementation found for method getLocalTimezone on channel flutter_timezone)
    at Object.d (http://aubin.localhost/main.dart.js:5407:19)
    at http://aubin.localhost/main.dart.js:103915:15
    at blw.a (http://aubin.localhost/main.dart.js:6787:63)
    at blw.$2 (http://aubin.localhost/main.dart.js:56568:14)
    at bka.$1 (http://aubin.localhost/main.dart.js:56562:21)
    at XP.F9 (http://aubin.localhost/main.dart.js:57753:33)
    at bas.$0 (http://aubin.localhost/main.dart.js:57036:11)
    at Object.Js (http://aubin.localhost/main.dart.js:6950:40)
    at ag.pt (http://aubin.localhost/main.dart.js:56961:3)
    at bal.$0 (http://aubin.localhost/main.dart.js:57006:13)
```

**Comment by miklcct** [comment]
Workaround:

```dart
final timezone = kIsWeb ? jsDateTimeFormat().resolvedOptions().timeZone : await FlutterTimezone.getLocalTimezone();
```

**Comment by peterprototypes** [comment]
I have the same issue. But it's with Firefox only. It works on Chrome in both debug and release mode.

**Comment by tjarvstrand** [comment]
Thanks for the report guys. For me, the example app is working in both Chrome (123.0.6312.122) and FF (124.0.1).

Do you get any console output at all? Could you provide me with a minimal reproducible example?

**Comment by miklcct** [comment]
I can no longer reproduce the issue after running `flutter clean` and rebuild the web.

**Comment by WieFel** [comment]
> I can no longer reproduce the issue after running `flutter clean` and rebuild the web.

had the same problem. this solved it
